export const t = {
  oneMoment: 'One moment please...',
  lobbyPrompt: 'What you you like to do?',
  join: 'Join a game',
  create: 'Create a game',
  choose: 'Choose a game',
  loginPrompt: 'Login or Register',
  login: 'Login',
  loggingIn: 'Logging in',
  register: 'Register',
  registration: 'Registration',
  emailPrompt: 'What is your email?',
  passwordPrompt: 'What is your password?',
  nicknamePrompt: 'What is your nickname?',
  failPrompt: ' failed. Please try again.',
  welcome: 'Welcome!',
  youSay: 'You say:',
  noGameFound: 'No games found',
}

